name: Release

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Build and publish MathJax
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: pnpm i

      - name: Build MathJax
        run: |
          ./components/bin/version
          pnpm -s link:src
          pnpm -s build-all
        
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks

